#React 앱 빌드
FROM node:20 AS builder
WORKDIR /app
COPY . .

ARG REACT_APP_YOUTUBE_API_KEY
ARG REACT_APP_REST_API_KEY
ARG REACT_APP_KAKAO_REDIRECT_URI
ARG REACT_APP_API_BASE_URL
ARG REACT_APP_KAKAO_REDIRECT_URL_BACK

ENV REACT_APP_YOUTUBE_API_KEY=$REACT_APP_YOUTUBE_API_KEY
ENV REACT_APP_REST_API_KEY=$REACT_APP_REST_API_KEY
ENV REACT_APP_KAKAO_REDIRECT_URI=$REACT_APP_KAKAO_REDIRECT_URI
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
ENV REACT_APP_KAKAO_REDIRECT_URL_BACK=$REACT_APP_KAKAO_REDIRECT_URL_BACK

RUN npm install && npm run build

#Nginx로 정적 파일 서빙
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
