name: Deploy Frontend (main)

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode EC2 SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Determine Active Stack
        id: check_stack
        run: |
          STACK=$(ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cat /home/ubuntu/current-stack.txt")
          if [ "$STACK" == "blue" ]; then
            echo "target_stack=green" >> "$GITHUB_OUTPUT"
          else
            echo "target_stack=blue" >> "$GITHUB_OUTPUT"
          fi

      - name: Set TARGET_STACK
        run: echo "Deploying to ${{ steps.check_stack.outputs.target_stack }}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build --no-cache \
            --build-arg REACT_APP_REST_API_KEY=${{ secrets.REACT_APP_REST_API_KEY }} \
            --build-arg REACT_APP_KAKAO_REDIRECT_URI=${{ secrets.REACT_APP_KAKAO_REDIRECT_URI }} \
            --build-arg REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} \
            --build-arg REACT_APP_KAKAO_REDIRECT_URL_BACK=${{ secrets.REACT_APP_KAKAO_REDIRECT_URL_BACK }} \
            --build-arg REACT_APP_YOUTUBE_API_KEY=${{ secrets.REACT_APP_YOUTUBE_API_KEY }} \
            -t ${{ secrets.DOCKER_USERNAME }}/cheftoo-frontend:${{ steps.check_stack.outputs.target_stack }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/cheftoo-frontend:${{ steps.check_stack.outputs.target_stack }}
      
      - name: Deploy to Dev Server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/cheftoo-frontend:${{ steps.check_stack.outputs.target_stack }}

          
            
